### ISSUE TITLE
Segmentation fault when installing via conda

### ISSUE THREAD

**Issue by boulund** [DerrickWood/kraken2#222]
It seems there is something wrong with the recent conda builds of kraken2. I could not run any of the available conda builds for version 2.0.7_beta and 2.0.8_beta. Just wanted to share in case anyone else encounters the same issue.

I noticed it when building a new conda environment to test something and Kraken2 produced a segfault for some input files that I know worked well using the kraken2 version that was installed in my base conda environment a while back. Here's the version I had installed compared to the version I recently installed in a fresh environment:

When running kraken2 from this environment it works:
```
(base) $ conda list | grep kraken2
kraken2                   2.0.8_beta      pl526hc9558a2_1    bioconda

(base) $ kraken2 --db /db/kraken2/kraken2_GRCh38 --threads 8 --output test.kraken --classified-out test#.classified.fq --unclassified-out test#.unclassified.fq --report test.kreport --paired --confidence 0.1 --quick sample3_1.fq.gz sample3_2.fq.gz                                                                                                           
Loading database information... done.                                                                                                        
995713 sequences (249.53 Mbp) processed in 7.623s (7837.2 Kseq/m, 1964.04 Mbp/m).                                                            
  20535 sequences classified (2.06%)                                                                                                         
  975178 sequences unclassified (97.94%)
```
When running kraken2 from this environment, it fails with `Segmentation fault (core dumped)`:
```
(base) $ conda create --yes -n kraken2_pl526hc9558a2_1 -c bioconda kraken2=2.0.8_beta=pl526hc9558a2_1
..... removed for brevity ...
(base) $ conda activate kraken2_pl526hc9558a2_1
(kraken2_test) $ conda list | grep kraken
kraken2                   2.0.8_beta      pl526hc9558a2_1    bioconda

(base) $ conda activate kraken2_pl526hc9558a2_1
(kraken2_pl526hc9558a2_1) $ kraken2 --db /db/kraken2/kraken2_GRCh38 --threads 8 --output test.kraken --classified-out test#.classified.fq --unclassified-out test#.unclassified.fq --report test.kreport --paired --confidence 0.1 --quick sample3_1.fq.gz sample3_2.fq.gz                                                                                        
Loading database information... done.                                                                                                        
Processed 995713 sequences (249531494 bp) ...Segmentation fault (core dumped)           
```
Note that exactly the same conda build as I have in my base env is installed in the new env.

Tried lots of stuff, installing older version via conda etc, and running some different Docker containers etc, and found recent conda installations to be the common denominator for all failing versions. To try to pinpoint the issue a bit more I was suggested to run `gdb`.

Since the main Perl wrapper script cannot be run directly with `gdb` I called `classify` manually. Output from `gdb` (here, again in a new conda environment I just built):
```
(kraken2_test) $ gdb --args ~/.conda/envs/kraken2_test/libexec/classify -H /db/kraken2/kraken2_GRCh38/hash.k2d -t /db/kraken2/kraken2_GRCh38/taxo.k2d -o /db/kraken2/kraken2_GRCh38/opts.k2d -q -T 0.1 -p 8 -P -R test.kreport -C test#.classified.fq -U test#.unclassified.fq -O test.kraken <(gunzip output_dir/fastp/sample3_1.fq.gz) <(gunzip output_dir/fastp/sample3_2.fq.gz)
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-115.el7                                                                                         
Copyright (C) 2013 Free Software Foundation, Inc.                                                                                            
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                                                
This is free software: you are free to change and redistribute it.                                                                           
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"                                                                   
and "show warranty" for details.                                                                                                             
This GDB was configured as "x86_64-redhat-linux-gnu".                                                                                        
For bug reporting instructions, please see:                                                                                                  
<http://www.gnu.org/software/gdb/bugs/>...                                                                                                   
Reading symbols from /home/fredrik.boulund/.conda/envs/kraken2_test/libexec/classify...done.                                                 
(gdb) r                                                                                                                                      
Starting program: /home/fredrik.boulund/.conda/envs/kraken2_test/libexec/classify -H /db/kraken2/kraken2_GRCh38/hash.k2d -t /db/kraken2/kraken2_GRCh38/taxo.k2d -o /db/kraken2/kraken2_GRCh38/opts.k2d -q -T 0.1 -p 8 -P -R test.kreport -C test\#.classified.fq -U test\#.unclassified.fq -O test.kraken /dev/fd/63 /dev/fd/62                                                                                                        
[Thread debugging using libthread_db enabled]                                                                                                
Using host libthread_db library "/lib64/libthread_db.so.1".                                                                                  
Loading database information... done.                                                                                                        
[New Thread 0x7fff01225780 (LWP 35624)]                                                                                                      
[New Thread 0x7fff00a23800 (LWP 35625)]                                                                                                      
[New Thread 0x7ffefbffe880 (LWP 35626)]                                                                                                      
[New Thread 0x7ffefb7fc900 (LWP 35627)]                                                                                                      
[New Thread 0x7ffefaffa980 (LWP 35628)]                                                                                                      
[New Thread 0x7ffefa7f8a00 (LWP 35629)]                                                                                                      
[New Thread 0x7ffef9ff6a80 (LWP 35630)]                                                                                                      
Program received signal SIGSEGV, Segmentation fault.                                                                                         
0x00007ffff7d3f4b9 in __kmpc_destroy_lock () from /home/fredrik.boulund/.conda/envs/kraken2_test/libexec/../lib/libgomp.so.1                 
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64                                                                
(gdb) bt                                                                                                                                     
#0  0x00007ffff7d3f4b9 in __kmpc_destroy_lock () from /home/fredrik.boulund/.conda/envs/kraken2_test/libexec/../lib/libgomp.so.1             
#1  0x0000555555564974 in kraken2::CompactHashTable::~CompactHashTable() ()                                                                  
#2  0x0000555555564999 in kraken2::CompactHashTable::~CompactHashTable() ()                                                                  
#3  0x0000555555558b74 in main ()                                         
```

I'm not entirely sure, but it seems to me like there is an issue with the OpenMP package from conda, so perhaps something has changed with the build for that package?

**Comment by maxibor** [comment]
Exactly the same problem here:
- With the older install of Kraken2 in my base conda env:
```bash
$ conda list | grep kraken2
kraken2                   2.0.8_beta      pl526hc9558a2_1    bioconda
$ kraken2 --db kraken \
        --threads 2 \
        --output metagenome.kraken.out \
        --report metagenome.kreport metagenome_Bacillus_subtilis.unaligned.fastq
Loading database information... done.
72181 sequences (6.59 Mbp) processed in 0.361s (12008.4 Kseq/m, 1096.02 Mbp/m).
  70384 sequences classified (97.51%)
  1797 sequences unclassified (2.49%)
```

- With the new install ok Kraken2 in a new env:
```bash
$ conda list | grep kraken2
kraken2                   2.0.8_beta      pl526hc9558a2_1    bioconda
$ kraken2 --db kraken \
        --threads 2 \
        --output metagenome.kraken.out \
        --report metagenome.kreport metagenome_Bacillus_subtilis.unaligned.fastq
Loading database information... done.
Processed 72181 sequences (6588042 bp) ...Segmentation fault (core dumped)
```

Running on Ubuntu 14.04.6 LTS server.

Any idea @Takadonet @DerrickWood @dfornika ?

**Comment by boulund** [comment]
I solved my issues with this by building a Singularity image where I compiled Kraken2 v2.0.8 from source, something like this def file (here based on the `continuumio/miniconda3` Docker image, because I wanted to have conda inside the container) :

```
Bootstrap: docker
From: continuumio/miniconda3

%environment
    PATH=/opt/kraken2-2.0.8-beta:/opt/conda/bin:$PATH
    export PATH

%post
	apt-get update && apt-get -y install \
		wget \
		zlib1g-dev \
		make \
		g++
	wget \
		https://github.com/DerrickWood/kraken2/archive/v2.0.8-beta.tar.gz \
		--output-document kraken2-2.0.8-beta.tar.gz
	tar -xvf kraken2-2.0.8-beta.tar.gz
	mkdir -pv /opt/kraken2-2.0.8-beta
	cd kraken2-2.0.8-beta
	./install_kraken2.sh /opt/kraken2-2.0.8-beta
	rm -rfv kraken2-2.0.8-beta*
```

**Comment by maxibor** [comment]
Adding test files:
database: [kraken.tar.gz](https://github.com/DerrickWood/kraken2/files/4319279/kraken.tar.gz)

fastq files: [metagenome_Bacillus_subtilis.unaligned.fastq.gz](https://github.com/DerrickWood/kraken2/files/4319280/metagenome_Bacillus_subtilis.unaligned.fastq.gz)

**Comment by BenLangmead** [comment]
Might be this issue?
https://software.intel.com/en-us/forums/intel-c-compiler/topic/291343

CC @DerrickWood

**Comment by maxibor** [comment]
I managed to find a conda based solution, but this drops the OSX support: this involves removing the llvm-openmp dependency, and the [patch](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kraken2/Makefile.patch).

Here is the `meta.yaml`
```yaml
{% set name = "kraken2" %}
{% set version = "2.0.8_beta" %}
{% set sha256 = "f2a91fc57a40b3e87df8ac2ea7c0ff1060cc9295c95de417ee53249ee3f7ad8e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DerrickWood/kraken2/archive/v2.0.8-beta.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  has_prefix_files:
    - libexec/kraken2
    - libexec/kraken2-build
    - libexec/kraken2-inspect

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - perl
  run:
    - perl
    - blast
    - rsync
    - wget
    - tar
test:
  commands:
    - kraken2 --version
    - kraken2-build --version
    - kraken2-inspect --version

about:
  home: http://ccb.jhu.edu/software/kraken/
  license: GPLv3
  license_file: LICENSE
  summary: Kraken is a system for assigning taxonomic labels to short DNA sequences, usually obtained through metagenomic studies.

extra:
  identifiers:
    - biotools:kraken2
    - doi:10.1186/gb-2014-15-3-r46
```

Here is the build.sh (unchanged):
```bash
#!/bin/bash


export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:${PREFIX}/include
export LIBRARY_PATH="${PREFIX}/lib"
export LD_LIBRARY_PATH="${PREFIX}/lib"

mkdir -p "$PREFIX/libexec" "$PREFIX/bin"

chmod u+x install_kraken2.sh
./install_kraken2.sh "$PREFIX/libexec"
for bin in kraken2 kraken2-build kraken2-inspect; do
    chmod +x "$PREFIX/libexec/$bin"
    ln -s "$PREFIX/libexec/$bin" "$PREFIX/bin/$bin"
    # Change from double quotes to single in case of special chars
    sed -i.bak "s#my \$KRAKEN_DIR = \"$PREFIX/libexec\";#my \$KRAKEN_DIR = '$PREFIX/libexec';#g" "$PREFIX/libexec/${bin}"
    rm -rf "$PREFIX/libexec/${bin}.bak"
done
```

It is available on my anaconda channel (only for linux-64): [anaconda.org/maxibor/kraken2](https://anaconda.org/maxibor/kraken2) - `conda install -c maxibor kraken2` before a fix is made available for the bioconda channel

**Comment by maxibor** [comment]
Though this will remain an issue as other conda package might add back `llvm-openmp` to an environment, and thus generate a segfault with Kraken2 @DerrickWood @BenLangmead

**Comment by jenniferlu717** [comment]
just fyi, we are not the ones that built/maintain the conda environment so this may be required to update the conda environment.

**Comment by maxibor** [comment]
It should be definitely fixed with [bioconda/bioconda-recipes#21535](https://github.com/bioconda/bioconda-recipes/pull/21535).
While the update is reviewed in bioconda, it is already available for Linux platforms in my personal channel `conda install -c maxibor kraken2`

**Comment by maxibor** [comment]
Bioconda recipe update merged, this issue can probably be closed @DerrickWood @jenniferlu717 @BenLangmead

**Comment by ialbert** [comment]
The problem still exists today on MacOS at least.

krake2 will fail with a seqmentation error once all the reads are classified and when the report needs to be generated.

**Comment by xzsword** [comment]
I re-download kraken2 by conda install -c maxibor kraken2 in another new conda env and kraken2 works! Thx a lot!
