### ISSUE TITLE
kraken2-build --download-library error for bacteria: ftp_path na

### ISSUE THREAD

**Issue by alxsimon** [DerrickWood/kraken2#226]
Hi,

When downloading the "bacteria" library through ftp I got the following error `rsync_from_ncbi.pl: unexpected FTP path (new server?) for na`.

It appears to be due to the presence of missing values `na` in the assembly_summary.txt file for the ftp_path variable used in the rsync_from_ncbi.pl script.

I imagine those recently appeared in the NCBI files as I did not find any issue about this.
Using Kraken version 2.0.8-beta installed with conda.

Maybe fail safes for such cases will be needed in the script?

**Comment by alxsimon** [comment]
A temporary workaround for now is to remove manually the `na`s from the `assembly_summary.txt`

```
awk -v FS='\t' '$20 != "na" {print $0}' assembly_summary.txt > new_assembly_summary.txt
cp new_assembly_summary.txt assembly_summary.txt
```

and to comment the `rm -f assembly_summary.txt` line in the `download_genomic_library.sh` script.

**Comment by jkin2003** [comment]
Where is the assembly_summary.txt file located? I'm looking through the directories and can not find it.

**Comment by alxsimon** [comment]
The location is here [ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt](url)
which is downloaded in `$DB/library/bacteria/`

You can see the `na`s with `cut -f 20 assembly_summary.txt | grep "^na$"` for example.

**Comment by jenniferlu717** [comment]
I noticed this just recently as well. I'll try to add in a workaround in the script to fix the error.

**Comment by maxmaronna** [comment]
Hello
Right now I am having the same error with archaea (but not with bacteria)

**Comment by SepOrion** [comment]
> Hello
> Right now I am having the same error with archaea (but not with bacteria).
> @alxsimon: what do you mean by "and to comment the rm -f assembly_summary.txt line in the download_genomic_library.sh script." Should add # in this line? (sorry if this is a silly question)

You can modify the rsync_from_ncbi.pl(miniconda3/envs/kraken2/libexec/rsync_from_ncbi.pl) file to solve this problem, add in the location of the picture.

  if (! ($full_path =~ s#^ftp://${qm_server}${qm_server_path}/##)) {
    die "$PROG: unexpected FTP path (new server?) for $ftp_path\n";
  }
![a](https://user-images.githubusercontent.com/43062054/78780786-be890d00-79d1-11ea-8192-24a1ab0d1e17.png)

**Comment by alxsimon** [comment]
> Hello
> Right now I am having the same error with archaea (but not with bacteria).
> @alxsimon: what do you mean by "and to comment the rm -f assembly_summary.txt line in the download_genomic_library.sh script." Should add # in this line? (sorry if this is a silly question)

Yes you could add a # before the line to avoid removing the file you just modified to remove the NAs.

But @SepOrion's solution is better.

**Comment by maxmaronna** [comment]
Hello alxsimon &  SepOrion 
The download worked the next day (I suppose this was the case because NCBI updates these files daily)...but now I have two alternatives in case a future problem like this.
Thanks a lot to both of you :)

**Comment by Phillip-a-richmond** [comment]
+1 on SepOrion's fix, here for those that want to copy+paste.

```
  my $full_path = $ftp_path . "/" . basename($ftp_path) . $suffix;
  # strip off server/leading dir name to allow --files-from= to work w/ rsync
  # also allows filenames to just start with "all/", which is nice

  ## Add from GitHub to overcome NA error during db build
  if ( $full_path =~/^na/){
  next
  }

  if (! ($full_path =~ s#^ftp://${qm_server}${qm_server_path}/##)) {
    die "$PROG: unexpected FTP path (new server?) for $ftp_path\n";
  }
```

**Comment by jenniferlu717** [comment]
We have just updated the code to include a fix. Using the latest kraken2 code, you should no longer have this problem.

**Comment by boyangzhang1993** [comment]
Thanks. encountered the same problem, solved by this method.

**Comment by xibalbanus** [comment]
I tried all the fixes suggested in this thread (alxsimon, SepOrion, and SolayMane) and I still get the same error. Only Univec_Core downloaded without issues. Any ideas/suggestions?

Cheers,

J.

**Comment by SolayMane** [comment]
please give more details what is the type of db you are trying to build ? give the command.

**Comment by xibalbanus** [comment]
`kraken2-build --download-library fungi --db nohuman
kraken2-build --download-library protozoa --db nohuman
kraken2-build --download-library plant --db nohuman
kraken2-build --download-library UniVec_Core --db nohuman`

Only the last one completed successfully. The other three resulted in `rsync_from_ncbi.pl: unexpected FTP path (new server?)`

**Comment by SolayMane** [comment]
give the output of :
```bash
find /home/ -type f -name "rsync_from_ncbi.pl"
````

**Comment by freixas84** [comment]
> To resolve the error "rsync_from_ncbi.pl: unexpected FTP path (new server?)", just replace in the file "libexec/rsync_from_ncbi.pl " "^ftp://" by "^https:// " in line 46.

You saved my day, that's a quick fix. Thanks a lot.

**Comment by kalonji08** [comment]
Hi @SolayMane @jenniferlu717 @SepOrion 
I have tried the suggestions but still getting the same error
here is how the rsync file looks like:

![image](https://user-images.githubusercontent.com/59872248/152371850-229b4871-3ba5-4ab3-98f5-c64a3eee0234.png)

**Comment by ssander5** [comment]
I am now getting the same error as @kalonji08 on the same file:
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1

the $full path hack isn't fixing this one either :(
