### ISSUE TITLE
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na

### ISSUE THREAD

**Issue by Laura-Alex** [DerrickWood/kraken2#292]
The strangest thing is that this worked just yesterday. I then deleted the database because something wasn't working in one of the downstream steps, tried to re-download it

`kraken2-build --download-library bacteria --db data-base --threads 32`

and the title error message is what I get. I've also tried using --use-ftp, but I still get an identical error message.  Help would be appreciated!

EDIT: Problem solved! I didn't change anything about my code and it worked. I guess there might've been issues on the NCBI side.
EDIT2: It stopped working again.

**Comment by igordot** [comment]
There is a potential fix posted in another issue: https://github.com/DerrickWood/kraken2/issues/226

**Comment by Laura-Alex** [comment]
> There is a potential fix posted in another issue: #226

Thank you, worked for me!

**Comment by jenniferlu717** [comment]
We have just updated the code to include a fix for this issue. If you continue to have problems with the newest code update, please open a new issue.

**Comment by snenish03** [comment]
I am using the latest version of Kraken2, and am still having this issue. Can you help?

**Comment by sidhu1969** [comment]
Downloaded ~35G then came up with rsync_from_ncbi.pl:FTP Connection error: Network is unreachable 
Nothing has changed - It didn't work last week, started working & then stopped again

**Comment by Gandasegui** [comment]
Same problem here. When running:
kraken2-build --download-library bacteria --db $DBNAME
I obtain:
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na

Any solutions?

**Comment by harshitakarri** [comment]
I am trying to create standard database in kraken2 for bacteria. Databases have been downloaded but i am encountering the obstacle when i am trying to build the database. 
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1
This is the error I have encountered.Kindly guide how to resolve the issue

**Comment by Cryphonectria** [comment]
I'm running into the exact same problem as harshitakarri
`kraken2-build --standard --threads 24 --db $DB --use-ftp`

```Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1
``` 
I installed kraken2 via conda. I saw on github that the scripts `rsync_from_ncbi.pl`  and `download_genomic_library.sh` were last edited 2 months ago, so I also tried to replace these scripts in my conda installation. However, no luck.

Any solutions for this?
Many thanks!

**Comment by sbs87** [comment]
This worked for me. Within the '**rsync_from_ncbi.pl'** script, there is a pattern matching operation for the ftp site. However, the returned addresses (stored in $full_path within the script) actually start with an _'https://'_ instead of _'ftp://'_ . Thus, I changed the following if statement regexp match line: 

`if (! ($full_path =~ s#^ftp://${qm_server}${qm_server_path}/##)) { 
die "$PROG: unexpected FTP path (new server?) for $ftp_path\n";
  }`

to: 

`if (! ($full_path =~ s#^https://${qm_server}${qm_server_path}/##)) {
die "$PROG: unexpected FTP path (new server?) for $ftp_path\n";
  }`

**Comment by sbs87** [comment]
@hebamuh68 within the scripts directory:
https://github.com/DerrickWood/kraken2/tree/master/scripts

**Comment by hebamuh68** [comment]
I used this tutorial,
[link](https://hackmd.io/@astrobiomike/kraken2-bracken-standard-build)
and inside the environment kraken2 I only found these files, there's no scripts.

![Screenshot from 2022-11-29 20-26-58](https://user-images.githubusercontent.com/69214737/204615442-9df0adad-98e3-447e-9f23-82094a55745e.png)

Instead of this 
`kraken2-build --standard --db kraken2-standard-db/ --threads 42`
I used `kraken2-build --standard --db kraken2-standard-db`
And also tried these ones:
- `kraken2-build --download-taxonomy --db kraken2-standard-db`
-  `kraken2-build --download-library bacteria --db kraken2-standard-db`
- `kraken2-build --download-library archaea --db raken2-standard-db`
- `kraken2-build --download-library viral --db kraken2-standard-db`

Sorry for all these explanation i've like a month trying to make this work.

**Comment by sbs87** [comment]
I would assume each of those commands still call on the 'rsync_from_ncbi.pl' script since this is the script that downloads the database from NCBI's ftp site. 

Can you poke around those folders? I would think the script is in bin or libexec  maybe?  Then you can try editing the script and re-running the above kraken2-build script.

**Comment by hebamuh68** [comment]
@sbs87 

I find it and replaced it like below

![image](https://user-images.githubusercontent.com/69214737/205039271-6636e00c-177e-4b5d-81ee-f3875c383ad0.png)

and it have been downloading for hours 

![image](https://user-images.githubusercontent.com/69214737/205039381-3a2d3ba9-ed13-4be4-9a3d-b7acadab84a4.png)

and when i check the file of database I find it created taxonomy folder but it's empty

**Comment by zhenghuawei923** [comment]
> > 在“ **rsync_from_ncbi.pl”**脚本中，
> 
> 请问这个脚本在哪里？
In conda directory,ll -d  your directory/anaconda/*/krake*|grep share
