### ISSUE TITLE
Will a minikraken2 database be made downloadable?

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#55]
I recall @jenniferlu717 said there was a `minikraken2` database being made available at some point?

Any update on this?

Would help a lot to get people installing tools dependent on `kraken2`.

**Comment by DerrickWood** [comment]
We're working on a dedicated Kraken 2 website now, which would have those MiniKraken DBs available. I expect it will be available in the next week or two.

**Comment by jenniferlu717** [comment]
oh the accuracy is fine, but I didn't want to provide the databases without also providing some statistics about them.

**Comment by Handymanalan** [comment]
Thanks Jennifer! Looking forward for the website.

Cheers

Alan

**Comment by SCTur** [comment]
Hi. I see that the minikraken2 database is up.  I am very new Linux and even newer to Kraken.  Could someone help me with the install code- I assume I need the kraken2-build code but instead of --standard, I need something else... is it just minikraken2?  I didn't see anything in the documentation. Thanks so much for your help getting me started.

**Comment by jenniferlu717** [comment]
MiniKraken databases are already built. All you need to do is download and unzip. You do not need to run kraken2-build at all. Just run kraken with the database = file containing the minikraken files (*.k2d files)

**Comment by alducluzeau** [comment]
Hi @jenniferlu717, 
After a recent install of kraken2 with homebrew, the classification with db minikraken2_v1 and v2 leads to "dump_table: Error reading in hash table". 
I get the same error message with the kraken2-inspect command on these two databases. 
However, my own built databases work just fine. 
Any idea?
Thank you very much!

**Comment by jenniferlu717** [comment]
I'll check this week!

**Comment by alducluzeau** [comment]
Jennifer,
I should have mentioned that minikraken2_v2 was working just fine with kraken2 when this one was installed from code source. I hope it will help. Thank you very much!

**Comment by jenniferlu717** [comment]
I'm going to rebuild minikraken for kraken2  and publish hopefully within the next 3 hours if not tomorrow.

**Comment by jenniferlu717** [comment]
Minikraken2_v1 has been updated - see http://ccb.jhu.edu/software/kraken2/index.shtml#downloads 

Minikraken2_v2 will be updated soon! (website link for v2 still points to the old one).

Let me know if you run into any problems with this

**Comment by fgravey** [comment]
Hello, 

I installed Kraken2 on my mac using brex yesterday and downloaded the two minikraken databases.

Unfortunately, I still having an issue which is : `dump_table: Error reading in hash table`

Thank you very much for your help

**Comment by jenniferlu717** [comment]
@fgravey which one are you having issues with? Both minikraken databases have been updated

**Comment by fgravey** [comment]
@jenniferlu717  Hello and thank you very much for you answer.

I have issues with both databases which have been downloaded the 2019-04-19 using the Kraken2 web site links.

**Comment by jfourquet2** [comment]
Hello,

I have this issue with kraken2-2.0.8-beta:
- all is ok when I create database
- issue when I run kraken2:

```
Unknown option: fastq-input
Loading database information...classify: Error reading in hash table
```

I published this comment in an other issue but this issue seems more appropriate.

Thanks a lot !

**Comment by tseemann** [comment]
@jfourquet2 the `-fastq-input` is an option in `kraken` (version 1). It is not in `kraken2`.

**Comment by jfourquet2** [comment]
@tseemann ok, thanks a lot ! I always have the issue `Loading database information...classify: Error reading in hash table` do you have an idea what is the problem ?

**Comment by alducluzeau** [comment]
@jenniferlu717: Hi Jennifer, I didn't come back to you on the matter. Sorry for that but I confirm @jfourquet2, despite your updates both databases do not with Kraken2 installed with Brew (Error reading in hash table). It's all fine with custom made databases. Sorry it' took me so long to come back to you.

**Comment by tseemann** [comment]
@jfourquet2 if you are using `conda` there was a bug in that both kraken packages put `classify` in the PATH and didn't use their local version. I think this has been fixed. Try `conda update kraken kraken2` maybe? or `conda update --all`

**Comment by alducluzeau** [comment]
Hi guys,

I tried: 
conda update --all 
but I still get 
Loading database information...classify: Error reading in hash table
when I try to classify with the April update of minikraken2_v1_8GB_201904_UPDATE.
I tried:
conda update kraken2
And I got
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/Anne-Lize/anaconda
  package name: kraken2
Any idea? Thank you.

**Comment by jfourquet2** [comment]
@tseemann  thanks for your answer !

**Comment by tseemann** [comment]
@alducluzeau there is (or was) a bug in conda where `classify` from kraken and kraken2 clashed and over-write each other. i don't know how to fix it.

**Comment by Praneet-Prabhanjan** [comment]
How to download the Minikraken2 database into my local system - Does Minikraken2 support 8 GB RAM? Can someone send me the command to download the Minikraken2 database in miniconda?
