### ISSUE TITLE
Building database fails

### ISSUE THREAD

**Issue by wyll-wyll-wyll** [DerrickWood/kraken2#922]
Hey there! I'm currently struggling to build the database to run Kraken2. I've download it using conda with the command line:

$ conda install -c bioconda kraken2

And then, at the next step of building the database, it just don't go through all the way. I've checked and storage space and memory doesn't seem to be the problem. I used the command line:

$ k2 build --standard --threads 24 --db krakenhaus --log log4krakenhaus

And the latest error that I got was:

"
/home/arun/miniconda3/envs/kraken2_env/bin/k2:1634: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall()
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/arun/miniconda3/envs/kraken2_env/lib/python3.13/concurrent/futures/process.py", line 254, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/arun/miniconda3/envs/kraken2_env/bin/k2", line 810, in assign_taxids
    with open(out_filepath, "w") as out_file:
         ~~~~^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'genomes/all/GCF/000/006/645/GCF_000006645.1_ASM664v1/GCF_000006645.1_ASM664v1_genomic.fna'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arun/miniconda3/envs/kraken2_env/bin/k2", line 3848, in <module>
    k2_main()
    ~~~~~~~^^
  File "/home/arun/miniconda3/envs/kraken2_env/bin/k2", line 3817, in k2_main
    build_standard_database(args)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/arun/miniconda3/envs/kraken2_env/bin/k2", line 2636, in build_standard_database
    download_genomic_library(args)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/arun/miniconda3/envs/kraken2_env/bin/k2", line 1961, in download_genomic_library
    sequence_to_url = assign_taxid_to_sequences(
        args, filepath_to_taxid_table,
        filepath_to_url=filepath_to_url
    )
  File "/home/arun/miniconda3/envs/kraken2_env/bin/k2", line 1214, in assign_taxid_to_sequences
    result = future.result()
  File "/home/arun/miniconda3/envs/kraken2_env/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/arun/miniconda3/envs/kraken2_env/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'genomes/all/GCF/000/006/645/GCF_000006645.1_ASM664v1/GCF_000006645.1_ASM664v1_genomic.fna'
"

Do you guys have any idea on how to overcome this issue? I've tried installing and building the database inside a designed conda environment, on my base environment, on my local machine, on my server, and it just won't go through all the way with the database building. I don't know what to do anymore. Any one has an ideia that could help?

**Comment by ch4rr0** [comment]
Thank you for reporting this issue. I see that you saved a log of the build process if possible can you post the log? This may be an issue caused by relative file paths. I will try to have it resolved today.

**Comment by ch4rr0** [comment]
I pushed a change to use absolute paths when processing the downloaded files. Can you test the change to find out if the resolves this issue?

**Comment by UofTDriv** [comment]
I am having a similar issue and I even fixed the deprecation warning with tar.extractall(filter="data") but k2 build is still failing on building archea here is the output
```
(k2wrappertestenv) [derivard@devhouse-new databases]$ k2 build --db k2wbtest/ --standard --max-db-size 16GB --threads 8
[INFO - 2025-06-19 10:31:19,145]: Downloading taxonomy tree data
[INFO - 2025-06-19 10:31:19,366]: Beginning download of ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz
[INFO - 2025-06-19 10:31:19,367]: Beginning download of ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz
[INFO - 2025-06-19 10:31:19,386]: Beginning download of ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
[INFO - 2025-06-19 10:31:22,913]: Calculating MD5 sum for /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/taxdump.tar.gz
[INFO - 2025-06-19 10:31:23,077]: MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/taxdump.tar.gz is 6aa74cd0b3c7dfb3552e29f2fef09869
[INFO - 2025-06-19 10:31:23,077]: The remote and local MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/taxdump.tar.gz match
[INFO - 2025-06-19 10:31:23,078]: Saved taxdump.tar.gz to /home/derivard/kraken2testing/databases/k2wbtest/taxonomy
[INFO - 2025-06-19 10:31:23,079]: Untarring taxonomy tree data
[INFO - 2025-06-19 10:31:26,603]: Finished Untarring taxonomy tree data
[INFO - 2025-06-19 10:32:21,953]: Calculating MD5 sum for /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_gb.accession2taxid.gz
[INFO - 2025-06-19 10:32:27,426]: MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_gb.accession2taxid.gz is d129c3451e474e686ed571beaa85c91c
[INFO - 2025-06-19 10:32:27,426]: The remote and local MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_gb.accession2taxid.gz match
[INFO - 2025-06-19 10:32:27,427]: Saved nucl_gb.accession2taxid.gz to /home/derivard/kraken2testing/databases/k2wbtest/taxonomy
[INFO - 2025-06-19 10:32:27,436]: Decompressing /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_gb.accession2taxid.gz
[INFO - 2025-06-19 10:32:43,115]: Calculating MD5 sum for /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_wgs.accession2taxid.gz
[INFO - 2025-06-19 10:32:55,545]: MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_wgs.accession2taxid.gz is a91005eb3ae32427a82b2cb52174ccb6
[INFO - 2025-06-19 10:32:55,545]: The remote and local MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_wgs.accession2taxid.gz match
[INFO - 2025-06-19 10:32:55,546]: Saved nucl_wgs.accession2taxid.gz to /home/derivard/kraken2testing/databases/k2wbtest/taxonomy
[INFO - 2025-06-19 10:32:55,556]: Decompressing /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_wgs.accession2taxid.gz
[INFO - 2025-06-19 10:33:22,638]: Finished decompressing /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_gb.accession2taxid.gz
[INFO - 2025-06-19 10:35:28,598]: Finished decompressing /home/derivard/kraken2testing/databases/k2wbtest/taxonomy/nucl_wgs.accession2taxid.gz
[INFO - 2025-06-19 10:35:33,593]: Adding archaea to /home/derivard/kraken2testing/databases/k2wbtest
[INFO - 2025-06-19 10:35:33,764]: Beginning download of ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt
[INFO - 2025-06-19 10:35:34,687]: Calculating MD5 sum for /home/derivard/kraken2testing/databases/k2wbtest/library/archaea/assembly_summary.txt
[INFO - 2025-06-19 10:35:34,691]: MD5 sum of /home/derivard/kraken2testing/databases/k2wbtest/library/archaea/assembly_summary.txt is 0ea2ff4f23fec3715bbe67a8d5bc79a6
[INFO - 2025-06-19 10:35:34,691]: Saved assembly_summary.txt to /home/derivard/kraken2testing/databases/k2wbtest/library/archaea
Traceback (most recent call last):
  File "/home/derivard/.conda/envs/k2wrappertestenv/bin/k2", line 4203, in <module>
    k2_main()
    ~~~~~~~^^
  File "/home/derivard/.conda/envs/k2wrappertestenv/bin/k2", line 4176, in k2_main
    build_standard_database(args)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/derivard/.conda/envs/k2wrappertestenv/bin/k2", line 2773, in build_standard_database
    download_genomic_library(args)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/derivard/.conda/envs/k2wrappertestenv/bin/k2", line 2057, in download_genomic_library
    filepath_to_taxid_table = make_manifest_from_assembly_summary(
        args, f
    )
  File "/home/derivard/.conda/envs/k2wrappertestenv/bin/k2", line 799, in make_manifest_from_assembly_summary
    asm_level_regex = "|".join(args.assembly_levels).replace("_", " ")
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'assembly_levels'
```

**Comment by tanmanpp** [comment]
Hi @UofTDriv did you solve the problem? I'm facing the same one and looking for a solution.

**Comment by ch4rr0** [comment]
I pushed a temporary fix for this issue. Can you try it out?
