### ISSUE TITLE
k2 download-library plasmid error

### ISSUE THREAD

**Issue by 543090lee** [DerrickWood/kraken2#925]
Hi,

I was running k2 download-library --db {DB_PATH} --library plasmid, and keep running into error. It finishes downloading all the gzipped plasmid files and saves them. But right after decompressing them, it outputs this error:

[ERROR - 2025-03-09 00:45:10,599]: Encountered error while downloading Plasmid library

**Comment by ch4rr0** [comment]
Thanks for reporting this! I pushed a potential fix to the master branch. Here is the diff:

``` diff
@@ -2013,7 +2013,7 @@ def download_genomic_library(args):
                     futures.append(future)
             result = concurrent.futures.wait(
                 futures,
-                return_when=concurrent.futures.FIRST_EXCEPTION
+                return_when=concurrent.futures.ALL_COMPLETED
             )
             if len(result.not_done) > 0:
                 LOG.error(

```

**Comment by 543090lee** [comment]
Thank you so much for the quick fix!

Has this been updated on Conda too?

**Comment by 543090lee** [comment]
Hi,

I have just tested the updated code, and it seems like there is still an issue. It runs without an error, but at the end, it outputs empty library.fna.

**Comment by ch4rr0** [comment]
Can you post the log here?

**Comment by ch4rr0** [comment]
I pushed a fix for the issue.

FYI -- you can add the `--threads <num_threads>` to your command line to speed up downloads and file processing.

**Comment by Samadhi9** [comment]
Hello, 

Is this issue resolved? I have the same problem. My command line k2 build --db [/path/] --standard --thread 64

Thank you,
Samadhi
